Repository jellyfin/Swiftfin, pull requests merged in 2025-07, with the labels that each got.

#1623 [iOS & tvOS] Fetch correct server from SwiftfinStore when updating server info
  Shared/SwiftfinStore/SwiftfinStore+ServerState.swift
Labels: bug, iOS, tvOS

#1614 `ActiveSessionsView` Cleanup
  Shared/Objects/ActiveSessionFilter.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/AdminDashboard/ActiveSessionsViewModel.swift
  Shared/ViewModels/AdminDashboard/ServerActivityViewModel.swift
  Swiftfin/Extensions/ButtonStyle-iOS.swift
  Swiftfin/Views/AdminDashboardView/ActiveSessions/ActiveSessionDetailView/Components/TranscodeSection.swift
  Swiftfin/Views/AdminDashboardView/ActiveSessions/ActiveSessionsView/ActiveSessionsView.swift
  Swiftfin/Views/AdminDashboardView/ActiveSessions/ActiveSessionsView/Components/ActiveSessionProgressSection.swift
  Swiftfin/Views/AdminDashboardView/ActiveSessions/ActiveSessionsView/Components/ActiveSessionRow.swift
  Swiftfin/Views/AdminDashboardView/ServerActivity/ServerActivityView/ServerActivityView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, iOS

#1632 Resolve `FlowLayout` Height Calculations
  Shared/Components/Layouts/FlowLayout.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactLogoScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/SimpleScrollView.swift
Labels: bug, iOS

#1635 Only log failed CoreStoreLogger assertions
  Shared/Logging/SwiftfinCorestoreLogger.swift
Labels: bug, developer

#1638 Fix `ItemView` Layout Issues for Uncached Images
  Swiftfin/Views/ItemView/Components/OffsetScrollView.swift
Labels: bug, iOS

#1653 Remove Non-Media Tracks from Video Player Dropdown
  Shared/Extensions/JellyfinAPI/MediaStream.swift
Labels: bug

#1655 Fix Linting Errors in `Main`
  Shared/SwiftfinStore/V2Schema/V2AnyData.swift
  Shared/ViewModels/ConnectToServerViewModel.swift
  Shared/ViewModels/HomeViewModel.swift
  Shared/ViewModels/ItemViewModel/ItemViewModel.swift
  Shared/ViewModels/UserProfileImageViewModel.swift
Labels: developer

#1583 Subtitle Management
  Shared/Components/ListRowCheckbox.swift
  Shared/Coordinators/Navigation/NavigationRoute/NavigationRoute+Item.swift
  Shared/Objects/MediaComponents/SubtitleFormat.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/ItemAdministration/ItemEditorViewModel/SubtitleEditorViewModel.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/ActionButtonHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/ItemSubtitleSearchView/Components/SubtitleSearchRow.swift
  Swiftfin tvOS/Views/ItemView/Components/ItemSubtitleSearchView/ItemSubtitleSearchView.swift
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Views/ItemEditorView/ItemEditorView.swift
  Swiftfin/Views/ItemEditorView/ItemSubtitles/Components/ItemSubtitleButton.swift
  Swiftfin/Views/ItemEditorView/ItemSubtitles/ItemSubtitleSearchView/Components/RemoteSubtitleButton.swift
  Swiftfin/Views/ItemEditorView/ItemSubtitles/ItemSubtitleSearchView/ItemSubtitleSearchView.swift
  Swiftfin/Views/ItemEditorView/ItemSubtitles/ItemSubtitleUploadView/ItemSubtitleUploadView.swift
  Swiftfin/Views/ItemEditorView/ItemSubtitles/ItemSubtitlesView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, low-priority, iOS, tvOS

#1634 [tvOS] Add Marquee to handle long season names
  Shared/Components/Marquee.swift
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/SeasonHStack.swift
Labels: enhancement, tvOS

#1658 [iOS/tvOS] Fix subtitle size
  Shared/Services/SwiftfinDefaults.swift
  Shared/ViewModels/VideoPlayerViewModel.swift
  Swiftfin/Views/VideoPlayer/LiveVideoPlayer.swift
  Swiftfin/Views/VideoPlayer/VideoPlayer.swift
Labels: bug, playback

#1656 [iOS] Remove UIScreen from CompactLogo & CompactPoster views
  Swiftfin/Views/ItemView/ScrollViews/CompactLogoScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactPortraitScrollView.swift
Labels: developer, iOS

#1639 Cleanup iPadOS `ItemView` TODOs
  Swiftfin/Views/ItemView/ScrollViews/iPadOSCinematicScrollView.swift
Labels: enhancement, developer, iOS

#1648 Limit Poster Image Quality
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Images.swift
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Poster.swift
  Shared/Extensions/JellyfinAPI/BaseItemPerson/BaseItemPerson+Poster.swift
  Shared/Extensions/JellyfinAPI/ChapterInfo.swift
  Shared/Objects/Poster/AnyPoster.swift
  Shared/Objects/Poster/Poster.swift
  Swiftfin tvOS/Components/PosterButton.swift
  Swiftfin tvOS/Views/ChannelLibraryView/Components/WideChannelGridItem.swift
  Swiftfin tvOS/Views/PagingLibraryView/Components/LibraryRow.swift
  Swiftfin/Components/PosterButton.swift
  Swiftfin/Views/AdminDashboardView/ActiveSessions/ActiveSessionsView/Components/ActiveSessionRow.swift
  Swiftfin/Views/AdminDashboardView/Components/MediaItemSection.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/AddItemElementView/Components/SearchResultsSection.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/EditItemElementView/Components/EditItemElementRow.swift
  Swiftfin/Views/PagingLibraryView/Components/LibraryRow.swift
Labels: enhancement, developer

#1661 [iOS/tvOS] Use Marquee in Playbutton to show media source
  Swiftfin tvOS/Views/ItemView/Components/PlayButton/PlayButton.swift
  Swiftfin/Views/ItemView/Components/PlayButton.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactPortraitScrollView.swift
Labels: enhancement, iOS, tvOS

#1616 Person `ItemView`
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto.swift
  Shared/ViewModels/ItemTypeCollection.swift
  Shared/ViewModels/ItemViewModel/CollectionItemViewModel.swift
  Shared/ViewModels/ItemViewModel/ItemViewModel.swift
  Shared/ViewModels/ItemViewModel/PersonItemViewModel.swift
  Swiftfin tvOS/Objects/FocusGuide.swift
  Swiftfin tvOS/Views/ItemView/CollectionItemContentView.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/ActionButtonHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/EpisodeHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/SeasonHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/OverviewView.swift
  Swiftfin tvOS/Views/ItemView/EpisodeItemContentView.swift
  Swiftfin tvOS/Views/ItemView/ItemView.swift
  Swiftfin tvOS/Views/ItemView/MovieItemContentView.swift
  Swiftfin tvOS/Views/ItemView/ScrollViews/CinematicScrollView.swift
  Swiftfin tvOS/Views/ItemView/SeriesItemContentView.swift
  Swiftfin tvOS/Views/SearchView.swift
  Swiftfin/Views/ItemEditorView/ItemEditorView.swift
  Swiftfin/Views/ItemView/CollectionItemContentView.swift
  Swiftfin/Views/ItemView/ItemView.swift
  Swiftfin/Views/ItemView/PersonItemContentView.swift
  Swiftfin/Views/ItemView/ScrollViews/CinematicScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactLogoScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactPortraitScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/SimpleScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/iPadOSCinematicScrollView.swift
Labels: enhancement, tvOS

#1672 Disable Liquid Glass/New Design Language
  Swiftfin tvOS/Resources/Info.plist
  Swiftfin/Resources/Info.plist
Labels: developer, iOS, tvOS
