Repository jellyfin/Swiftfin, pull requests merged in 2025-04, with the labels that each got.

#1456 [iOS & tvOS] Trailers
  Shared/Objects/TrailerSelection.swift
  Shared/Strings/Strings.swift
  Shared/SwiftfinStore/StoredValue/StoredValues+User.swift
  Shared/ViewModels/ItemViewModel/ItemViewModel.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButton.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/ActionButtonHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/Components/RefreshMetadataButton.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/Components/TrailerMenu.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtons/ActionButton.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtons/ActionMenu.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtons/VersionMenu.swift
  Swiftfin tvOS/Views/ItemView/Components/PlayButton/Components/VersionMenu.swift
  Swiftfin tvOS/Views/ItemView/Components/PlayButton/PlayButton.swift
  Swiftfin tvOS/Views/ItemView/EpisodeItemView/EpisodeItemContentView.swift
  Swiftfin tvOS/Views/ItemView/ScrollViews/CinematicScrollView.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin/Views/ItemView/Components/ActionButton/ActionButton.swift
  Swiftfin/Views/ItemView/Components/ActionButtonHStack.swift
  Swiftfin/Views/ItemView/Components/ActionButtonHStack/ActionButtonHStack.swift
  Swiftfin/Views/ItemView/Components/ActionButtonHStack/Components/TrailerMenu.swift
  Swiftfin/Views/ItemView/Components/ActionButtonHStack/Components/VersionMenu.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement

#1468 [tvOS] Move AddUserButton to the bottom bar of Select User View
  Shared/Components/AlternateLayoutView.swift
  Shared/Components/CenteredLazyVGrid.swift
  Shared/Components/ConditionalMenu.swift
  Shared/Extensions/ViewExtensions/Modifiers/ScrollIfLargerThanContainerModifier.swift
  Shared/Extensions/ViewExtensions/ViewExtensions.swift
  Shared/Objects/SelectUserServerSelection.swift
  Swiftfin tvOS/Views/SelectUserView/Components/AddUserBottomButton.swift
  Swiftfin tvOS/Views/SelectUserView/Components/AddUserButton.swift
  Swiftfin tvOS/Views/SelectUserView/Components/AddUserGridButton.swift
  Swiftfin tvOS/Views/SelectUserView/Components/SelectUserBottomBar.swift
  Swiftfin tvOS/Views/SelectUserView/Components/ServerSelectionMenu.swift
  Swiftfin tvOS/Views/SelectUserView/SelectUserView.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement

#1474 [tvOS] Stops the `SeasonHStack` Shadow from Clipping
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/SeasonHStack.swift
Labels: bug

#1466 [iOS & tvOS] Fix Square Overlay Over Profiles
  Shared/Components/UserProfileImage/UserProfileImage.swift
  Swiftfin tvOS/Views/SelectUserView/Components/UserGridButton.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUsersView/Components/ServerUsersRow.swift
  Swiftfin/Views/SelectUserView/Components/UserGridButton.swift
  Swiftfin/Views/SelectUserView/Components/UserRow.swift
Labels: bug

#1481 [tvOS] Fix First Login Crash
  Swiftfin tvOS/Views/UserSignInView/UserSignInView.swift
Labels: bug, crash

#1473 [tvOS] Various Setting Cleanup
  Shared/Strings/Strings.swift
  Swiftfin tvOS/Components/ListRowMenu.swift
  Swiftfin tvOS/Components/OrderedSectionSelectorView.swift
  Swiftfin tvOS/Components/SplitFormWindowView.swift
  Swiftfin tvOS/Views/FontPickerView.swift
  Swiftfin tvOS/Views/ServerDetailView.swift
  Swiftfin tvOS/Views/SettingsView/CustomDeviceProfileSettingsView/Components/EditCustomDeviceProfileView.swift
  Swiftfin tvOS/Views/SettingsView/CustomDeviceProfileSettingsView/CustomDeviceProfileSettingsView.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/CustomizeViewsSettings.swift
  Swiftfin tvOS/Views/SettingsView/IndicatorSettingsView.swift
  Swiftfin tvOS/Views/SettingsView/UserProfileSettingsView/UserProfileSettingsView.swift
  Swiftfin tvOS/Views/SettingsView/VideoPlayerSettingsView.swift
  Swiftfin tvOS/Views/UserSignInView/UserSignInView.swift
  Swiftfin/Views/SettingsView/CustomDeviceProfileSettingsView/Components/EditCustomDeviceProfileView.swift
  Swiftfin/Views/SettingsView/CustomDeviceProfileSettingsView/CustomDeviceProfileSettingsView.swift
  Swiftfin/Views/SettingsView/GestureSettingsView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement

#1483 [Meta] Cleanup Jellyfin Version Badge
  README.md
Labels: documentation

#1484 Cleanup `ChevronButton`
  Shared/Components/ChevronAlertButton.swift
  Shared/Components/ChevronButton.swift
  Shared/Extensions/URL.swift
  Swiftfin tvOS/Views/AppSettingsView/AppSettingsView.swift
  Swiftfin tvOS/Views/AppSettingsView/Components/SignOutIntervalSection.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/HomeSection.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/LibrarySection.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/CustomizeViewsSettings.swift
  Swiftfin tvOS/Views/SettingsView/PlaybackQualitySettingsView.swift
  Swiftfin tvOS/Views/SettingsView/SettingsView.swift
  Swiftfin tvOS/Views/SettingsView/UserProfileSettingsView/UserLocalSecurityView.swift
  Swiftfin tvOS/Views/SettingsView/UserProfileSettingsView/UserProfileSettingsView.swift
  Swiftfin tvOS/Views/SettingsView/VideoPlayerSettingsView.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin/Views/AboutAppView.swift
  Swiftfin/Views/AdminDashboardView/AdminDashboardView.swift
  Swiftfin/Views/AdminDashboardView/ServerTasks/AddTaskTriggerView/Components/IntervalRow.swift
  Swiftfin/Views/AdminDashboardView/ServerTasks/AddTaskTriggerView/Components/TimeLimitSection.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserDetailsView/ServerUserDetailsView.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserSettings/ServerUserPermissionsView/Components/Sections/ExternalAccessSection.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserSettings/ServerUserPermissionsView/Components/Sections/SessionsSection.swift
  Swiftfin/Views/AppSettingsView/AppSettingsView.swift
  Swiftfin/Views/ItemEditorView/ItemEditorView.swift
  Swiftfin/Views/ItemEditorView/ItemImages/ItemImageDetailsView/Components/ItemImageDetailsDetailsSection.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/EditMetadataView/Components/Sections/EpisodeSection.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/EditMetadataView/Components/Sections/ReviewsSection.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/EditMetadataView/Components/Sections/SeriesSection.swift
  Swiftfin/Views/MediaSourceInfoView.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/Components/Sections/HomeSection.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/CustomizeViewsSettings.swift
  Swiftfin/Views/SettingsView/PlaybackQualitySettingsView.swift
  Swiftfin/Views/SettingsView/SettingsView/SettingsView.swift
  Swiftfin/Views/SettingsView/UserProfileSettingsView/UserProfileSettingsView.swift
  Swiftfin/Views/SettingsView/VideoPlayerSettingsView/Components/Sections/ButtonSection.swift
  Swiftfin/Views/SettingsView/VideoPlayerSettingsView/Components/Sections/SubtitleSection.swift
  Swiftfin/Views/SettingsView/VideoPlayerSettingsView/VideoPlayerSettingsView.swift
  Swiftfin/Views/VideoPlayer/Components/PlaybackSettingsView.swift
Labels: enhancement, developer

#1491 [Meta] Fix Webplates
  Scripts/Translations/AlphabetizeStrings.swift
  Translations/en.lproj/Localizable.strings
Labels: bug, developer

#1485 [iOS] Admin Dashboard - User Activity
  Shared/Coordinators/AdminDashboardCoordinator.swift
  Shared/Extensions/JellyfinAPI/ActivityLogEntry.swift
  Shared/Extensions/JellyfinAPI/LogLevel.swift
  Shared/Extensions/Sequence.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/AdminDashboard/ServerActivityDetailViewModel.swift
  Shared/ViewModels/AdminDashboard/ServerActivityViewModel.swift
  Shared/ViewModels/AdminDashboard/ServerUsersViewModel.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin/Views/AdminDashboardView/ActiveSessions/ActiveSessionDetailView/ServerSessionDetailView.swift
  Swiftfin/Views/AdminDashboardView/AdminDashboardView.swift
  Swiftfin/Views/AdminDashboardView/Components/MediaItemSection.swift
  Swiftfin/Views/AdminDashboardView/ServerActivity/ServerActivityDetailsView/ServerActivityDetailsView.swift
  Swiftfin/Views/AdminDashboardView/ServerActivity/ServerActivityView/Components/ServerActivityEntry.swift
  Swiftfin/Views/AdminDashboardView/ServerActivity/ServerActivityView/ServerActivityView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement

#1498 [iOS & tvOS] Fix Recently Added Missing Movies
  Shared/Objects/ItemFilter/ItemFilterCollection.swift
  Shared/ViewModels/LibraryViewModel/RecentlyAddedViewModel.swift
Labels: bug

#1488 [iOS] Admin Dashboard - QuickConnect Other User
  Shared/Coordinators/AdminDashboardCoordinator.swift
  Shared/Coordinators/SettingsCoordinator.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/QuickConnectAuthorizeViewModel.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Swiftfin/Components/ListRowButton.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserDetailsView/ServerUserDetailsView.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Swiftfin/Views/SettingsView/UserProfileSettingsView/QuickConnectAuthorizeView.swift
  Swiftfin/Views/SettingsView/UserProfileSettingsView/UserProfileSettingsView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement

#1489 [iOS] Admin Dashboard - Allowed Tags Cleanup
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserSettings/ServerUserAccessTags/EditServerUserAccessTagsView/EditServerUserAccessTagsView.swift
Labels: bug

#1504 [iOS & tvOS] Improve rounded corner performance
  Shared/Extensions/ViewExtensions/ViewExtensions.swift
Labels: enhancement, developer

#1497 [iOS] Replace Gear Icon with User Icon Only
  Shared/Extensions/ViewExtensions/ViewExtensions.swift
  Swiftfin/Components/SettingsBarButton.swift
Labels: bug

#1507 [iOS & tvOS] Explicitly request transparent logos
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+Images.swift
Labels: bug

#1499 [iOS & tvOS] Cleanup Permission Validation
  Shared/Extensions/JellyfinAPI/BaseItemKind.swift
  Shared/Objects/UserPermissions.swift
  Shared/Strings/Strings.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/ActionButtonHStack.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Swiftfin/Views/ItemEditorView/ItemEditorView.swift
  Swiftfin/Views/ItemView/ItemView.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/Components/Sections/ItemSection.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, developer

#1517 [iOS] Preserve vector data in preview app icons
  Swiftfin/Resources/Assets.xcassets/AppIcon-dark-blue.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-dark-green.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-dark-jellyfin.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-dark-orange.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-dark-red.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-dark-yellow.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedDark-blue.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedDark-green.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedDark-jellyfin.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedDark-orange.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedDark-red.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedDark-yellow.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedLight-blue.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedLight-green.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedLight-jellyfin.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedLight-orange.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedLight-red.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-invertedLight-yellow.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-light-blue.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-light-green.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-light-jellyfin.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-light-orange.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-light-red.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-light-yellow.imageset/Contents.json
  Swiftfin/Resources/Assets.xcassets/AppIcon-primary-primary.imageset/Contents.json
Labels: enhancement, iOS

#1519 [tvOS] Follow the User's Preference for Poster Type in the Latest Section
  Swiftfin tvOS/Views/HomeView/Components/LatestInLibraryView.swift
Labels: bug, tvOS

#1518 [tvOS] Fix Next Up Overlapping with TabBar
  Swiftfin tvOS/Views/HomeView/HomeView.swift
Labels: bug, tvOS

#1526 Move `RedrawOnNotificationView.swift`
  Shared/Components/RedrawOnNotificationView.swift
  Swiftfin.xcodeproj/project.pbxproj
Labels: developer
