Repository jellyfin/Swiftfin, pull requests merged in 2025-03, with the labels that each got.

#1446 [tvOS] Season Selector Scrolling Bug
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/EpisodeHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/SeasonHStack.swift
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/EpisodeSelector.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin/Views/ItemView/Components/EpisodeSelector/Components/EpisodeHStack.swift
Labels: bug

#1449 [iOS & tvOS] Video Range Types
  Shared/Components/AttributeBadge.swift
  Shared/Extensions/JellyfinAPI/MediaStream.swift
  Shared/Extensions/VideoRangeType.swift
  Shared/Extensions/ViewExtensions/Modifiers/AttributeStyleModifier.swift
  Shared/Extensions/ViewExtensions/ViewExtensions.swift
  Swiftfin tvOS/Views/ItemView/Components/AttributeHStack.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Views/ItemView/Components/AttributeHStack.swift
Labels: enhancement

#1447 [tvOS] Sign-In Flow - User Auto Time-Out
  Shared/Coordinators/AppSettingsCoordinator.swift
  Shared/Extensions/ViewExtensions/ViewExtensions.swift
  Swiftfin tvOS/Views/AppSettingsView/Components/HourMinutePicker.swift
  Swiftfin tvOS/Views/AppSettingsView/Components/SignOutIntervalSection.swift
  Swiftfin tvOS/Views/SettingsView/VideoPlayerSettingsView.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: enhancement

#1445 [iOS] Fix External Subtitle Selection
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+VideoPlayerViewModel.swift
  Shared/Extensions/JellyfinAPI/MediaStream.swift
  Shared/Extensions/JellyfinAPI/SubtitleProfile.swift
  Shared/ViewModels/VideoPlayerViewModel.swift
Labels: bug

#1450 [Meta] Library & Playback Documentation
  Documentation/libraries.md
  Documentation/players.md
Labels: documentation

#1453 [iOS] External display wide ratio support
  Swiftfin/Views/VideoPlayer/NativeVideoPlayer.swift
Labels: enhancement

#1451 [tvOS] "Native" Styled Menu Button
  Swiftfin tvOS/Components/InlineEnumToggle.swift
  Swiftfin tvOS/Components/ListRowMenu.swift
  Swiftfin tvOS/Views/AppSettingsView/AppSettingsView.swift
  Swiftfin tvOS/Views/AppSettingsView/Components/SignOutIntervalSection.swift
  Swiftfin tvOS/Views/ServerDetailView.swift
  Swiftfin tvOS/Views/SettingsView/CustomDeviceProfileSettingsView/CustomDeviceProfileSettingsView.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/LibrarySection.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/CustomizeViewsSettings.swift
  Swiftfin tvOS/Views/SettingsView/PlaybackQualitySettingsView.swift
  Swiftfin tvOS/Views/SettingsView/SettingsView.swift
  Swiftfin.xcodeproj/project.pbxproj
Labels: enhancement

#1454 [Meta] Add External Display to Player Documentation
  Documentation/players.md
Labels: documentation
