Repository jellyfin/Swiftfin, pull requests merged in 2025-06, with the labels that each got.

#1552 Reverting to VLCKit 3.5.0 | solving OPUS issue
  Cartfile
Labels: bug, developer, playback

#1556 Cinematic Episode Image
  Swiftfin/Views/ItemView/ScrollViews/iPadOSCinematicScrollView.swift
Labels: bug, iOS

#1455 Drop iOS 15
  Swiftfin.xcodeproj/project.pbxproj
Labels: enhancement, developer, iOS

#1565 iOS 16 README
  README.md
Labels: documentation

#1490 Get Localizations from Jellyfin & Apple
  Shared/Components/Localization/CountryPicker.swift
  Shared/Components/Localization/CulturePicker.swift
  Shared/Extensions/JellyfinAPI/CountryInfo.swift
  Shared/Extensions/JellyfinAPI/CultureDto.swift
  Shared/ViewModels/BaseFetchViewModel.swift
  Shared/ViewModels/Localization/CountriesViewModel.swift
  Shared/ViewModels/Localization/CulturesViewModel.swift
  Shared/ViewModels/Localization/ParentalRatingsViewModel.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Components/CountryPicker.swift
  Swiftfin/Components/LanguagePicker.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/EditMetadataView/Components/Sections/LocalizationSection.swift
Labels: enhancement, iOS, tvOS

#1569 Replace `WrappingHStack` for `FlowLayout`
  Shared/Components/AttributeBadge.swift
  Shared/Components/Layouts/FlowLayout.swift
  Swiftfin tvOS/Views/ItemView/Components/AttributeHStack.swift
  Swiftfin tvOS/Views/ItemView/EpisodeItemView/EpisodeItemContentView.swift
  Swiftfin tvOS/Views/ItemView/ScrollViews/CinematicScrollView.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Views/ItemView/Components/AttributeHStack.swift
  Swiftfin/Views/ItemView/ScrollViews/CinematicScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactLogoScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactPortraitScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/SimpleScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/iPadOSCinematicScrollView.swift
Labels: enhancement, developer, iOS

#1578 Use `xcconfig`
  .gitignore
  Documentation/contributing.md
  Swiftfin.xcodeproj/project.pbxproj
  XcodeConfig/Shared.xcconfig
Labels: developer

#1587 Add File Information to `IdentifyItemView`
  Swiftfin/Views/ItemEditorView/IdentifyItemView/IdentifyItemView.swift
Labels: enhancement, iOS

#1594 Fix logging
  Shared/Extensions/CoreStore.swift
  Shared/Extensions/Nuke/ImagePipeline.swift
  Shared/Extensions/PersistentLogHandler.swift
  Shared/Logging/Logging.swift
  Shared/Logging/NetworkLogger.swift
  Shared/Logging/SwiftfinCorestoreLogger.swift
  Shared/Services/LogManager.swift
  Shared/Services/UserSession.swift
  Shared/SwiftfinStore/SwiftfinStore+ServerState.swift
  Shared/SwiftfinStore/SwiftinStore+UserState.swift
  Shared/ViewModels/ConnectToServerViewModel.swift
  Swiftfin tvOS/App/SwiftfinApp.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/App/SwiftfinApp.swift
Labels: enhancement, developer

#1604 Update action Xcode version
  .github/workflows/ci.yml
Labels: developer

#1605 Fix Show Icon
  Shared/Coordinators/Tabs/MainTabView.swift
Labels: bug, tvOS

#1609 Coordinator `.Sheet` Cleanup
  Shared/Coordinators/Navigation/NavigationRoute/NavigationRoute+Admin.swift
  Shared/Coordinators/Navigation/NavigationRoute/NavigationRoute+Item.swift
  Shared/ViewModels/ItemAdministration/RefreshMetadataViewModel.swift
  Swiftfin tvOS/Components/OrderedSectionSelectorView.swift
  Swiftfin/Views/AdminDashboardView/ServerActivity/ServerActivityFilterView/ServerActivityFilterView.swift
  Swiftfin/Views/AdminDashboardView/ServerActivity/ServerActivityView/ServerActivityView.swift
  Swiftfin/Views/AppSettingsView/AppSettingsView.swift
  Swiftfin/Views/ItemEditorView/IdentifyItemView/Components/RemoteSearchResultView.swift
  Swiftfin/Views/ItemEditorView/IdentifyItemView/IdentifyItemView.swift
  Swiftfin/Views/ItemEditorView/ItemImages/AddItemImageView.swift
  Swiftfin/Views/ItemEditorView/ItemImages/ItemImageDetailsView/ItemImageDetailsView.swift
  Swiftfin/Views/ItemEditorView/ItemImages/ItemImagesView.swift
  Swiftfin/Views/ItemEditorView/ItemImages/ItemPhotoPickerView/ItemPhotoPickerView.swift
Labels: enhancement, developer, iOS

#1610 Cleanup Player Documentation
  Documentation/players.md
Labels: documentation, enhancement
