Repository jellyfin/Swiftfin, pull requests merged in 2025-05, with the labels that each got.

#1510 Implement localization for hardcoded strings
  Shared/Components/TruncatedText.swift
  Shared/Extensions/JellyfinAPI/SortOrder+ItemSortOrder.swift
  Shared/Objects/CustomDeviceProfileAction.swift
  Shared/Objects/GestureAction.swift
  Shared/Objects/OverlayType.swift
  Shared/Objects/PosterDisplayType.swift
  Shared/Objects/SliderType.swift
  Shared/Objects/TimeStampType.swift
  Shared/Objects/TrailingTimestampType.swift
  Shared/Objects/UserAccessPolicy.swift
  Shared/Objects/VideoPlayerType/VideoPlayerType.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/AdminDashboard/DeviceDetailViewModel.swift
  Shared/ViewModels/SelectUserViewModel.swift
  Shared/ViewModels/UserLocalSecurityViewModel.swift
  Swiftfin tvOS/Views/ServerDetailView.swift
  Swiftfin/Components/LearnMoreButton.swift
  Swiftfin/Components/ListTitleSection.swift
  Swiftfin/Views/ChannelLibraryView/ChannelLibraryView.swift
  Swiftfin/Views/EditServerView.swift
  Swiftfin/Views/PagingLibraryView/Components/LibraryViewTypeToggle.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/CustomizeViewsSettings.swift
  Swiftfin/Views/UserSignInView/Components/UserSignInSecurityView.swift
  Swiftfin/Views/VideoPlayer/LiveVideoPlayer.swift
  Swiftfin/Views/VideoPlayer/VideoPlayer+KeyCommands.swift
  Swiftfin/Views/VideoPlayer/VideoPlayer.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, developer

#1542 Bump LePip's Collection Packages to Latest Commits
  Swiftfin tvOS/Views/ItemView/Components/EpisodeSelector/Components/HStacks/EpisodeHStack.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Views/ItemView/Components/EpisodeSelector/Components/EpisodeHStack.swift
  Swiftfin/Views/VideoPlayer/Overlays/ChapterOverlay.swift
Labels: bug, external

#1544 Fix typo in string triggerAlreadyExists
  Shared/Strings/Strings.swift
  Translations/en.lproj/Localizable.strings
Labels: bug

#1543 Cleanup `ItemView`s
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto.swift
  Shared/Strings/Strings.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Views/ItemView/CollectionItemContentView.swift
  Swiftfin/Views/ItemView/EpisodeItemContentView.swift
  Swiftfin/Views/ItemView/ItemView.swift
  Swiftfin/Views/ItemView/MovieItemContentView.swift
  Swiftfin/Views/ItemView/ScrollViews/CinematicScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactLogoScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/CompactPortraitScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/SimpleScrollView.swift
  Swiftfin/Views/ItemView/ScrollViews/iPadOSCinematicScrollView.swift
  Swiftfin/Views/ItemView/SeriesItemContentView.swift
  Swiftfin/Views/ItemView/iOS/CollectionItemView/CollectionItemContentView.swift
  Swiftfin/Views/ItemView/iOS/CollectionItemView/CollectionItemView.swift
  Swiftfin/Views/ItemView/iOS/EpisodeItemView/EpisodeItemContentView.swift
  Swiftfin/Views/ItemView/iOS/EpisodeItemView/EpisodeItemView.swift
  Swiftfin/Views/ItemView/iOS/MovieItemView/MovieItemView.swift
  Swiftfin/Views/ItemView/iOS/SeriesItemView/SeriesItemView.swift
  Swiftfin/Views/ItemView/iPadOS/CollectionItemView/iPadOSCollectionItemView.swift
  Swiftfin/Views/ItemView/iPadOS/EpisodeItemView/iPadOSEpisodeItemView.swift
  Swiftfin/Views/ItemView/iPadOS/MovieItemView/iPadOSMovieItemContentView.swift
  Swiftfin/Views/ItemView/iPadOS/MovieItemView/iPadOSMovieItemView.swift
  Swiftfin/Views/ItemView/iPadOS/SeriesItemView/iPadOSSeriesItemContentView.swift
  Swiftfin/Views/ItemView/iPadOS/SeriesItemView/iPadOSSeriesItemView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, developer

#1546 optimize: Send media source id to playback info
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto+VideoPlayerViewModel.swift
Labels: enhancement, playback
