Repository jellyfin/Swiftfin, pull requests merged in 2025-09, with the labels that each got.

#1696 [iOS/tvOS] Fix user icons not changing between servers
  Shared/Components/CenteredLazyVGrid.swift
Labels: bug

#1706 Bump Introspect Version
  Shared/Extensions/ViewExtensions/Backport/Backport.swift
  Shared/Extensions/ViewExtensions/Modifiers/ScrollViewOffsetModifier.swift
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug, developer

#1712 [iOS] Fix audio/subtitle tracks not changing
  Swiftfin/Views/VideoPlayerContainerView/PlaybackControls/Components/NavigationBar/ActionButtons/AudioActionButton.swift
  Swiftfin/Views/VideoPlayerContainerView/PlaybackControls/Components/NavigationBar/ActionButtons/SubtitleActionButton.swift
Labels: bug, playback

#1714 `Stateful` macro
  .github/workflows/ci.yml
  Shared/Components/Localization/CountryPicker.swift
  Shared/Components/Localization/CulturePicker.swift
  Shared/Components/Localization/ParentalRatingPicker.swift
  Shared/Coordinators/Navigation/NavigationRoute/NavigationRoute+Download.swift
  Shared/Coordinators/Navigation/WithTransitionReaderPublisher.swift
  Shared/Coordinators/Tabs/TabItemSelectedPublisher.swift
  Shared/Extensions/UIDevice.swift
  Shared/Objects/EventPublisher.swift
  Shared/Objects/Eventful.swift
  Shared/Objects/MediaPlayerManager/MediaPlayerManager.swift
  Shared/Objects/Stateful.swift
  Shared/Objects/Utilities.swift
  Shared/ViewModels/BaseFetchViewModel.swift
  Shared/ViewModels/ConnectToServerViewModel.swift
  Shared/ViewModels/ItemAdministration/RefreshMetadataViewModel.swift
  Shared/ViewModels/Localization/ParentalRatingsViewModel.swift
  Shared/ViewModels/MediaViewModel/MediaViewModel.swift
  Shared/ViewModels/QuickConnectAuthorizeViewModel.swift
  Shared/ViewModels/SelectUserViewModel.swift
  Shared/ViewModels/ServerCheckViewModel.swift
  Shared/ViewModels/ServerConnectionViewModel.swift
  Shared/ViewModels/ServerLogsViewModel.swift
  Shared/Views/MediaView/Components/MediaItem.swift
  Shared/Views/MediaView/MediaView.swift
  Swiftfin tvOS/Views/ConnectToServerView/ConnectToServerView.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/Components/RefreshMetadataButton.swift
  Swiftfin tvOS/Views/MediaView/Components/MediaItem.swift
  Swiftfin tvOS/Views/MediaView/MediaView.swift
  Swiftfin tvOS/Views/SelectUserView/SelectUserView.swift
  Swiftfin tvOS/Views/VideoPlayerContainerState/PlaybackControls/VideoPlayerContainerView.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Extensions/ButtonStyle-iOS.swift
  Swiftfin/Views/AdminDashboardView/ServerLogsView/ServerLogsView.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserSettings/ServerUserParentalRatingView/ServerUserParentalRatingView.swift
  Swiftfin/Views/ConnectToServerView.swift
  Swiftfin/Views/ItemEditorView/Components/RefreshMetadataButton.swift
  Swiftfin/Views/SelectUserView/SelectUserView.swift
  Swiftfin/Views/ServerCheckView.swift
  Swiftfin/Views/SettingsView/UserProfileSettingsView/QuickConnectAuthorizeView.swift
Labels: enhancement, developer

#1718 `Stateful` Macro - `APIKeysViewModel` & `AddServerUserViewModel`
  Shared/Extensions/Array.swift
  Shared/Extensions/ViewExtensions/Modifiers/ErrorMessage.swift
  Shared/Extensions/ViewExtensions/ViewExtensions.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/AdminDashboard/APIKeysViewModel.swift
  Shared/ViewModels/AdminDashboard/ActiveSessionsViewModel.swift
  Shared/ViewModels/AdminDashboard/AddServerUserViewModel.swift
  Shared/ViewModels/ConnectToServerViewModel.swift
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Swiftfin/Views/AdminDashboardView/APIKeyView/APIKeysView.swift
  Swiftfin/Views/AdminDashboardView/APIKeyView/Components/APIKeysRow.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/AddServerUserView/AddServerUserView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, developer

#1719 Pin `Transmission` and fix severe hang
  PreferencesView/Package.swift
  PreferencesView/Sources/PreferencesView/UIPreferencesHostingController.swift
  PreferencesView/Sources/PreferencesView/ViewExtensions.swift
  Shared/Components/WithObservedObject.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Labels: bug, crash

#1720 `Stateful` Macro - Server Devices & Details
  Shared/Coordinators/Navigation/NavigationRoute/NavigationRoute+Admin.swift
  Shared/Strings/Strings.swift
  Shared/ViewModels/AdminDashboard/DeviceDetailViewModel.swift
  Shared/ViewModels/AdminDashboard/DevicesViewModel.swift
  Swiftfin.xcodeproj/project.pbxproj
  Swiftfin/Views/AdminDashboardView/ServerDevices/DeviceDetailsView/Components/Sections/CustomDeviceNameSection.swift
  Swiftfin/Views/AdminDashboardView/ServerDevices/DeviceDetailsView/DeviceDetailsView.swift
  Swiftfin/Views/AdminDashboardView/ServerDevices/DevicesView/DevicesView.swift
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserSettings/ServerUserDeviceAccessView/ServerUserDeviceAccessView.swift
  Translations/en.lproj/Localizable.strings
Labels: enhancement, developer

#1723 Change one instance of "ratings" string for "parentalRating"
  Swiftfin/Views/AdminDashboardView/ServerUsers/ServerUserDetailsView/ServerUserDetailsView.swift
Labels: bug

#1724 Settings Fixes
  Shared/Strings/Strings.swift
  Swiftfin tvOS/Views/SettingsView/CustomizeViewsSettings/Components/Sections/HomeSection.swift
  Swiftfin/Views/ItemEditorView/ItemMetadata/EditMetadataView/Components/Sections/ReviewsSection.swift
  Swiftfin/Views/SettingsView/CustomizeViewsSettings/Components/Sections/HomeSection.swift
  Translations/en.lproj/Localizable.strings
Labels: bug

#1742 Chapters Fix
  Shared/Extensions/JellyfinAPI/BaseItemDto/BaseItemDto.swift
  Shared/Extensions/JellyfinAPI/ChapterInfo.swift
  Shared/Objects/MediaPlayerManager/PreviewImageProvider/ChapterPreviewImageProvider.swift
  Shared/Objects/MediaPlayerManager/PreviewImageProvider/PreviewImageProvider.swift
  Shared/Objects/MediaPlayerManager/PreviewImageProvider/TrickplayPreviewImageProvider.swift
  Shared/Objects/MediaPlayerManager/Supplements/MediaChaptersSupplement.swift
  Shared/ViewModels/ServerCheckViewModel.swift
  Swiftfin/Views/VideoPlayerContainerView/PlaybackControls/Components/PlaybackProgress/ChapterTrackMask.swift
  Swiftfin/Views/VideoPlayerContainerView/PlaybackControls/Components/PlaybackProgress/PlaybackProgress.swift
  Swiftfin/Views/VideoPlayerContainerView/PlaybackControls/Components/PlaybackProgress/PreviewImageView.swift
Labels: bug

#1744 remove old logService and replace instances with new Logger.swiftfin()
  Shared/Logging/Logging.swift
  Shared/ServerDiscovery/ServerDiscovery.swift
  Shared/Services/DownloadManager.swift
  Shared/Services/DownloadTask.swift
  Shared/SwiftfinStore/StoredValue/StoredValue.swift
  Shared/SwiftfinStore/SwiftfinStore.swift
  Shared/ViewModels/ViewModel.swift
  Swiftfin tvOS/Views/ItemView/Components/ActionButtonHStack/Components/TrailerMenu.swift
  Swiftfin/Views/ItemView/Components/ActionButtonHStack/Components/TrailerMenu.swift
Labels: enhancement, developer

#1750 Fix Incorrect Icon for Subtitles
  Swiftfin/Views/VideoPlayerContainerView/PlaybackControls/Components/NavigationBar/ActionButtons/SubtitleActionButton.swift
Labels: bug
